export { default as About } from './about.component/About.component';
export { default as Contact } from './contact.component/Contact.component';
export { default as CreatePlan } from './create-plan.component/CreatePlan.component';
export { default as Dashboard } from './dashboard.component/Dashboard.component';
export { default as Home } from './home.component/Home.component';
export { default as NotFound } from './not-found.component/NotFound.component';
export { default as PlanView } from './plan-view.component/PlanView.component';
export { default as PlansList } from './plans-list.component/PlansList.component';
export { default as SignIn } from './sign-in.component/SignIn.component';
